on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
    paths-ignore:
      - "README.md"

  pull_request:

  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job:
              os: ubuntu-18.04
              build: ./src/net50/run.sh
            tests:
              framework: net5.0
              sdk: "5.0.401"
          - job:
              os: ubuntu-20.04
              build: ./src/net50/run.sh
            tests:
              framework: net5.0
              sdk: "5.0.401"
          - job:
              os: windows-2019
              build: ./src/net50/run.cmd
            tests:
              framework: net5.0
              sdk: "5.0.401"
          - job:
              os: windows-2022
              build: ./src/net50/run.cmd
            tests:
              framework: net5.0
              sdk: "5.0.401"
          - job:
              os: macos-10.15
              build: ./src/net50/run.sh
            tests:
              framework: net5.0
              sdk: "5.0.401"
          - job:
              os: macos-11
              build: ./src/net50/run.sh
            tests:
              framework: net5.0
              sdk: "5.0.401"
    name: ${{ matrix.job.os }}-${{ matrix.tests.framework }}
    runs-on: ${{ matrix.job.os }}
    steps:
      - name: setup-dotnet tests-sdk
        if: ${{ matrix.tests.sdk != '5.0.401' }}
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: "${{ matrix.tests.sdk }}"
      - uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: "5.0.401"
      - name: Run dotnet --info
        run: dotnet --info
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Build
        run: ${{ matrix.job.build }}
